### ISSUE TITLE
Define a Software Steering Council representative

### ISSUE THREAD

**Issue by choldgraf** [jupyter-book/team-compass#5]
The Jupyter [Software Steering Council](https://jupyter.org/governance/software_steering_council.html#software-steering-council) is a body comprised of one representative from each sub-project. They make project-wide decisions about software standards, direction, etc. They are the main group that writes and votes on JEPs.

We need to select an SSC rep for Jupyter Book. This is an issue to track this!

Generally speaking SSC reps are members of a Steering Council, but I believe that any member of a sub-project is eligible.

**Comment by Ruv7** [comment]
Hi y'all. Following up on this, any updates? Subprojects are required to have an SSC rep and we want to close the loop on this sooner than later. This is important in the scenario that the SSC takes any important votes in the near term.

**Comment by Ruv7** [comment]
Brilliant! Thanks Angus for filling this role. I would also ask that you add this info to the Leadership Directory: https://jupyter.org/governance/people.html
