### ISSUE TITLE
Renew the myst.md domain for another year

### ISSUE THREAD

**Issue by choldgraf** [jupyter-book/team-compass#8]
Our myst.md domain expires on September 28th, we need to renew it for another year. I mentioned it to @rowanc1 who agreed that we should go ahead and do this, even though we aren't using it right now because of security purposes (non-standard URL domains aren't consistently available to people in security-minded organizations like government)

**Comment by choldgraf** [comment]
I went ahead and paid for 4 years of registration. Screenshot attached below It will expire on September 28th. It will expire on **September 28th, 2029**. Who knows what the world will look like then so that's far enough in the future that we won't have to worry about this for a while :-)

![CleanShot 2024-09-22 at 10 03 47@2x](https://github.com/user-attachments/assets/37b9d4a1-b835-42d0-82e0-4f938263885c)

I'll try to submit a reimbursement through CS&S for this, it's about $100.

**Comment by rowanc1** [comment]
🚀
